networks:
  hikeease-network:
    driver: bridge

services:
  hikeease-app:
    context: .
    build: .Dockerfile
    image: nginx:latest
    container_name: "hikeease"

  nginx:
    restart: always
    container_name: "nginx"
    image: nginx:latest
    ports:
      - "443:443"
    depends_on:
      - hikeease-app
    volumes:
      - .nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/hike.pem:/etc/ssl/certs/hikeease.pem:rw
      - ./ssl/nso_indosatooredoo_com.key:/etc/ssl/private/hikeease.key:rw
    networks:
      - hikeease-network