networks:
  hikeease-network:
    driver: bridge

services:
  hikeease-app:
    build: .
    image: hikeease-app:latest
    container_name: "hikeease"
    ports:
    - 5000
    volumes:
    - /hikeease/.:/hikeease

  nginx:
    restart: always
    container_name: "nginx"
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - hikeease-app
    volumes:
      - /hikeease/nginx.conf:/etc/nginx/nginx.conf:rw
      # - ./ssl/hike.pem:/etc/ssl/certs/hikeease.pem:rw
      # - ./ssl/nso_indosatooredoo_com.key:/etc/ssl/private/hikeease.key:rw
    networks:
      - hikeease-network