networks:
  hikeease-network:
    driver: bridge

services:
  hikeease-app:
    build: .
    image: hikeease-app:latest
    container_name: "hikeease"
    ports:
    - 5000:5000
    volumes:
    - /hikeease/.:/hikeease
    networks:
      - hikeease-network

  nginx:
    restart: always
    container_name: "nginx"
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - hikeease-app
    volumes:
      - /hikeease/nginx.conf:/etc/nginx/nginx.conf:rw
      - /hikeease/ssl/certificate.crt:/etc/ssl/certs/certificate.crt:rw
      - /hikeease/ssl/certificate.key:/etc/ssl/private/certificate.key:rw
    networks:
      - hikeease-network