networks:
  hikeease-network:
    driver: bridge

services:
  hikeease-app:
    build: .
    image: hikeease-app:latest
    container_name: "hikeease"
    volumes:
    - /hikeease/.:/hikeease
    networks:
      - hikeease-network

  nginx:
    restart: always
    container_name: "nginx"
    image: nginx:latest
    ports:
      - "443:443"
    depends_on:
      - hikeease-app
    volumes:
      - /hikeease/nginx.conf:/etc/nginx/nginx.conf:rw
      - /hikeease/ssl/certificate.pem:/etc/ssl/certs/certificate.pem:rw
      - /hikeease/ssl/private.key:/etc/ssl/private/private.key:rw
    networks:
      - hikeease-network